language: ruby
os: linux
dist: bionic
rvm: "— 2.6.5"
addons:
    postgresql: '10.10'
    # uncomment when needed, will save us time
    # chrome: stable
    code_climate:
        repo_token:
            secure: "KeKYrK0GYKSXbbCVniFeRXcEEO6DRy/4CEiatJFlSSrG910zAwjxTze74s/iK6w3EVR4tjvBqnP25z0kli0yop6O13jPKE39+JSn6cYjsFYdbdCZPnq2p4bopxF5CI0gxpgiMxDC2Xy8obbhkwWoQjXAXWUgPXrEjfC2KaKc0mE5BGYwW1+WR2tlwH5R+Zq19V6N0xi/YmyG4SvIY0kjdNQXgjEdlg3YzCsPwx2mqE4loc77XWCIjE22jUujQnPbSCDSHWkp9eNBEd4xFMu0i9kH1WxOi7a27ok/Smm7FuAK7aEWZpnjLYG44g7WvFGgOuReTzKGpuju/Ksdz7q4xr10sxITXA/sZHqEwbTXAFjchfhSkEGDvUEdeaLch+la0REwLs8ZDPiQN3G07cK9ZLHa/J8h7TAk+7b7TjoL7b6FHDLf9QmmJsvLTYmyYbgStFl1aJNEbswiOuEiT+yM4CuRHIJlApF17W9p6IPK2qu0pN/2qtseRolegSwjjjfsw946T4SGGpChQ1vxeXvYeTT8N5aQtz/cndiG356yjFwywxot9kxHdHu0kFTXFOllbcFTudRyfMmjnf8mcuXty1zENOJZf6LKFyZOgjqXKepEo4zmvuV7S9VNIUg5Y9+Q4tc7oIjGvZZ7vRyuYQBe0KTn2zsKelFYYEAME8DDNZQ="
services:
- postgresql
# uncomment when needed, will save us time
#- redis

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

notifications:
  email: false
  slack:
    rooms:
      secure: tC0FMV4JnuSSxmaiuwvqiiBcEeBU0jn3rnZINc1UgjGW6fiGVtY2i2Ht7Zud0v0jrw+TDIkt25O6y6e1irmvvS0B2ryoF7QjUwMjp9Y76gg9TvcQML6JxM/b7TujWNxTxVKxB7wfGyozQteOaS8nbGiOkQL476Q9W3bpA//O1UWRx82qgTHIoCIT05bx+DKP2qlYynsVOJyBDDWCIApQOdkfO79v2NZ6p+82fnjLM77oVckUCt0ZYWe0yry40RjObDBRCjGBx0TMxO/K4x6JcQIs0L+eEJOpc02IpQu4CPH/ZWKBvNmVGw30nTJSBZRCcdatOOEy2SiT1lXrRpkQ8Kb1xRuz2h/vM0pd1dtsRbIIDUCQ329dkjrkcNBcwrkKrHvBRgybLJYAPg9N6LjjQPV5TlCPVhOa5HiJ6bq6eClEasWvFhQQM057wkB7cyqd6zPzENRvHup1sdlq+ZXxAc69cqsizfxvVxQC20Znoe+Bs2Gqsu/jNbuDW3JYvqaYdc8OX6l95vIBoLg+rJ4OOfUYnTcXh6160uY7V77wwzOKibzvTsrjaeaMay+KCGn57m4rjY3UlbhjzLw8IlDl9o4Z2KLxAUKCjtEwAtB2hAdbbxsvpppmqR8Sj9A9FRMdzLkCpHwiSX3D7wf9Y3iU8tHr39FIeeytfQpx3ODZSnc=
    on_success: change # default: always

env:
  global:
    secure: eJtjCStS+HmQzEZw+/xoQOPBXnNI9YKp3XhBQ9pmlztoE22nrGbJJoLt6kcpu9LQHSAG8rqduWIKuRKfZmqPtNmIbFSB2f+5Ie4lVC9TGNWQV4nIzV/RqTMUiDASEYB8KDIfiA97jDYLpMDegj7fqMWqQz7oH1NXcbQdjq2UkcwprUBNvMC2fxHAEaOQtPcSjJS6rKNCVn/FiSQr6+pE6G2rcGFywnP/sToPTg8SSkIdGLCWk5y3UHkTe2s83nEWw9ujj8Kv0p6cexlJVMzMd8O0+C2OANFZaS+kqmTXLBpvzpDjurvwRkW+9j7wiJRf47NG84ZvE4XB1xfF5qYaA4ZqsFU6TcHAotEOCMzwOCHNN1Gpe0pgYyd1xPhVFPWf+CauAkiBlAFfCdiMn7PdOv0KYBLbFSPR7hsBuWxlP2bdzqsuHKQJUoCgsR9tuHLxPVPrybCeKTkN3pony2rYp7ymxvbPJQF2ugmDLcLJ/uwyNjsBNUDUmhNGUycwhBT0XRUoc6cqRcVZAnELdTHw33bKRn5qf+O3GXqe/koMBI0SSIBGnXR8UJMlE5Ce8mYjRLT7c+UWIgPJnwKmv/WMxTF1LYnu0iiqJcX90kPT05xe+3xhTUDFOsnXMfdndg72RuDtmeAV4La7bT2/7+HHJUU9nFJBtWQpeuQ8Xxw3ZXM=
